# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_oauth2_google
description: This package contains the needed elements to connect to a OAuth 2.0 Client through
  Google Identity Provider.
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7

  # Easily create managers
  act_abstract_manager:
    path: ../act_abstract_manager

  act_config_manager:
    path: ../act_config_manager

  act_dart_utility:
    path: ../act_dart_utility

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

  # Core library for OAuth 2.0
  act_oauth2_core:
    path: ../act_oauth2_core

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
