# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_thingsboard_client
description: Helpful package to use the Thingsboard client with app
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  thingsboard_client:
    git:
      url: https://github.com/benoit-rolandeau-act/dart_thingsboard_client.git
      ref: based-on-v1.4.0


  # Help to implement value based equality without explicit override
  equatable: ^2.0.5

  mutex: ^3.0.1

  act_dart_utility:
    path: ../act_dart_utility

  act_server_req_manager:
    path: ../act_server_req_manager

  act_stores_manager:
    path: ../act_stores_manager

  # Flutter AC Technologies dependencies
  act_abstract_manager:
    path: ../act_abstract_manager

  act_env_manager:
    path: ../act_env_manager

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

