# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_location_manager
description: This package is useful to get location from phones

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  # Handle realtime location
  geolocator: ^14.0.1

  act_abs_peripherals_manager:
    path: ../act_abs_peripherals_manager

  act_abstract_manager:
    path: ../act_abstract_manager

  act_enable_service_utility:
    path: ../act_enable_service_utility

  act_global_manager:
    path: ../act_global_manager

  act_life_cycle_manager:
    path: ../act_life_cycle_manager

  act_logger_manager:
    path: ../act_logger_manager

  act_permissions_manager:
    path: ../act_permissions_manager

  act_platform_manager:
    path: ../act_platform_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^5.0.0
