# SPDX-FileCopyrightText: 2024 Th√©o Magne <theo.magne@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_aws_iot_core
description: "Package to interact with aws iot core using amplify credentials"
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_flutter: ^2.5.0

  amplify_auth_cognito: ^2.5.0

  aws_common: ^0.7.4

  aws_signature_v4: ^0.6.3

  equatable: ^2.0.5

  mqtt_client: ^10.5.1

  mutex: ^3.1.0

  uuid: ^4.4.2

  # Contains the structure to create services and managers
  act_abstract_manager:
    path: ../act_abstract_manager

  act_amplify_cognito:
    path: ../act_amplify_cognito

  # This contains the amplify core library
  act_amplify_core:
    path: ../act_amplify_core

  act_config_manager:
    path: ../act_config_manager

  act_dart_utility:
    path: ../act_dart_utility

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Internet access. For ObserverInternet
  act_internet_connectivity_manager:
    path: ../act_internet_connectivity_manager

  # Contains the logger manager
  act_logger_manager:
    path: ../act_logger_manager

  # Shared auth classes. For the ObserverAuth
  act_shared_auth:
    path: ../act_shared_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
