name: act_thingsboard
description: This package contains all the needed class to communicate with Thingsboard
author: AC Technologies
version: 0.0.2

publish_to: none

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  act_abstract_manager:
    git:
      url: ssh://git@gitlab.act.lan:2211/internal-libraries/software/actflutterpackages.git
      ref: act_abstract_manager_0.0.1
      path: act_abstract_manager

  act_dart_utility:
    git:
      url: ssh://git@gitlab.act.lan:2211/internal-libraries/software/actflutterpackages.git
      ref: act_dart_utility_0.0.1
      path: act_dart_utility

  act_entity:
    git:
      url: ssh://git@gitlab.act.lan:2211/internal-libraries/software/actflutterpackages.git
      ref: act_entity_0.0.1
      path: act_entity

  act_global_manager:
    git:
      url: ssh://git@gitlab.act.lan:2211/internal-libraries/software/actflutterpackages.git
      ref: act_global_manager_0.0.2
      path: act_global_manager

  act_life_cycle_manager:
    git:
      url: ssh://git@gitlab.act.lan:2211/internal-libraries/software/actflutterpackages.git
      ref: act_life_cycle_manager_0.0.1
      path: act_life_cycle_manager

  act_logger_manager:
    git:
      url: ssh://git@gitlab.act.lan:2211/internal-libraries/software/actflutterpackages.git
      ref: act_logger_manager_0.0.1
      path: act_logger_manager

  act_stores_manager:
    git:
      url: ssh://git@gitlab.act.lan:2211/internal-libraries/software/actflutterpackages.git
      ref: act_stores_manager_0.0.2
      path: act_stores_manager

  act_server_request_manager:
    git:
      url: ssh://git@gitlab.act.lan:2211/internal-libraries/software/actflutterpackages.git
      ref: act_server_request_manager_0.0.2
      path: act_server_request_manager

  equatable: ^1.2.5

  tuple: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
