# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_web_local_storage_manager
description: This package contains the web local storage manager
publish_to: none

# This package supports all platforms listed below.
platforms:
  web:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  web: ^1.1.1

  act_abstract_manager:
    path: ../act_abstract_manager

  act_config_manager:
    path: ../act_config_manager

  act_dart_utility:
    path: ../act_dart_utility

  act_global_manager:
    path: ../act_global_manager

  act_local_storage_manager:
    path: ../act_local_storage_manager

  act_logger_manager:
    path: ../act_logger_manager
