# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: actlibs
description: This package contains all the packages created by ACT office for Flutter applications.
publish_to: none

environment:
  sdk: ^3.6.0

dev_dependencies:
  mono_repo: ^6.6.2
  flutter_lints: ^5.0.0
  pana: ^0.22.17
