# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_halo_ble_layer
description: This is the BLE hardware layer for the HALO protocol

publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.13.0

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  mutex: ^3.1.0

  uuid: ^4.5.1

  # Easily create managers
  act_abstract_manager:
    path: ../act_abstract_manager

  act_ble_manager:
    path: ../act_ble_manager

  # Extend Dart functionalities
  act_dart_utility:
    path: ../act_dart_utility

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  act_halo_abstract:
    path: ../act_halo_abstract

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^5.0.0
