# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_ble_manager
description: This package contains the base for Bluetooth Low Energy
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.13.0

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  # Library to handle BLE for multiple devices
  flutter_reactive_ble: ^5.4.0

  # Mutual exclusion with implementation of normal and read-write mutex
  mutex: ^3.1.0

  act_abs_peripherals_manager:
    path: ../act_abs_peripherals_manager

  act_abstract_manager:
    path: ../act_abstract_manager

  act_config_manager:
    path: ../act_config_manager

  # Extend Dart functionalities
  act_dart_utility:
    path: ../act_dart_utility

  act_enable_service_utility:
    path: ../act_enable_service_utility

  act_flutter_utility:
    path: ../act_flutter_utility

  act_global_manager:
    path: ../act_global_manager

  act_life_cycle_manager:
    path: ../act_life_cycle_manager

  act_logger_manager:
    path: ../act_logger_manager

  act_permissions_manager:
    path: ../act_permissions_manager

  act_platform_manager:
    path: ../act_platform_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^5.0.0
