# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_server_req_manager
description: Useful to request third servers
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Help to implement value based equality without explicit override
  equatable: ^2.0.5

  # Future-based API for HTTP requests
  http: ^1.2.2

  # Easily create managers
  act_abstract_manager:
    path: ../act_abstract_manager

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

  # Shared auth library
  act_shared_auth:
    path: ../act_shared_auth

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
