# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_tic_manager
description: This package contains a tic manager which helps to display HMI in pace
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: 0.28.0

  act_abstract_manager:
    path: ../act_abstract_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
