# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_ble_manager_ui
description: "This contains ui elements to complete the ACT BLE manager"
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  # Implement the BLoC (Business Logic Component) design pattern
  flutter_bloc: ^9.1.1

  # Mutual exclusion with implementation of normal and read-write mutex
  mutex: ^3.1.0

  act_ble_manager:
    path: ../act_ble_manager

  act_global_manager:
    path: ../act_global_manager

  act_logger_manager:
    path: ../act_logger_manager

  act_router_manager:
    path: ../act_router_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
