# SPDX-FileCopyrightText: 2024 Th√©o Magne <theo.magne@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_consent_manager
description: "This package contains useful methods and classes to manage user consents."
publish_to: none

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Create widget from markdown string
  # TODO(brolandeau): the package is discontinued, need to find another one
  flutter_markdown: ^0.7.7+1

  equatable: ^2.0.7

  mutex: ^3.1.0

  # Easily create managers
  act_abstract_manager:
    path: ../act_abstract_manager

  # Utility
  act_dart_utility:
    path: ../act_dart_utility

  # Internet access
  act_internet_connectivity_manager:
    path: ../act_internet_connectivity_manager

  act_intl:
    path: ../act_intl

  # Authentification lib
  act_shared_auth:
    path: ../act_shared_auth

  # Global manager
  act_global_manager:
    path : ../act_global_manager

  # Loggers
  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
