# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_http_client_jwt_auth
description: Contains specific server authentication to work with JWT
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_jsonwebtoken: ^3.2.0

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  # Easily create managers
  act_abstract_manager:
    path: ../act_abstract_manager

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  act_http_client_manager:
    path: ../act_http_client_manager

  act_http_core:
    path: ../act_http_core

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

  # Shared auth library
  act_shared_auth:
    path: ../act_shared_auth

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

