# SPDX-FileCopyrightText: 2020 - 2023 Sami Kouatli <sami.kouatli@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

# Project definition
name: act_flutter_utility
description: This package contains useful methods and classes which extends flutter functionality.

# Project configuration
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

# Project dependencies
dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  # Help to implement value based equality without explicit override
  equatable: ^2.0.5

  # Implement the BLoC (Business Logic Component) design pattern
  flutter_bloc: ^9.1.0

  # SVG image widget
  flutter_svg: ^2.0.10+1

  # Tells which amount a widget is currently visible
  visibility_detector: ^0.4.0+2

  act_config_manager:
    path: ../act_config_manager

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Help to know the current internet state on the phone (if we can join internet, or not)
  act_internet_connectivity_manager:
    path: ../act_internet_connectivity_manager

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

# Dependencies used by developer
dev_dependencies:
  # API to test Flutter applications
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^5.0.0
