# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_thingsboard_client_ui
description: This package contains widgets, BLoCs and other classes useful to display information 
  from thingsboard servers.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Help to implement value based equality without explicit override
  equatable: 2.0.7

  # Implement the BLoC (Business Logic Component) design pattern
  flutter_bloc: 9.1.1

  # Mutual exclusion with implementation of normal and read-write mutex
  mutex: 3.1.0

  thingsboard_client:
    git:
      url: https://github.com/benoit-rolandeau-act/dart_thingsboard_client.git
      ref: fix-tb-storage-interface

  act_dart_utility:
    path: ../act_dart_utility

  act_flutter_utility:
    path: ../act_flutter_utility

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  act_internet_connectivity_manager:
    path: ../act_internet_connectivity_manager

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

  act_thingsboard_client:
    path: ../act_thingsboard_client

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
