# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_server_req_jwt_logins
description: Contains specific server logins to work with JWT
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_jsonwebtoken: ^2.14.1

  # Help to implement value based equality without explicit override
  equatable: ^2.0.5

  # Easily create managers
  act_abstract_manager:
    path: ../act_abstract_manager

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

  act_server_req_manager:
    path: ../act_server_req_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

