# SPDX-FileCopyrightText: 2024 Th√©o Magne <theo.magne@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_server_storage_manager
description: "Act server storage manager package."
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7

  # Used to cache files
  flutter_cache_manager: ^3.4.1

  # Helps manipulating paths
  path: ^1.9.1

  # Used to get the application directory (cache, documents, etc.)
  path_provider: ^2.1.5

  # Easily create managers
  act_abstract_manager:
    path: ../act_abstract_manager

  # Provide the configuration for the storage manager
  act_config_manager:
    path: ../act_config_manager

  # Global manager
  act_global_manager:
    path : ../act_global_manager

  # Loggers
  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
