# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_amplify_core
description: "This is the package to manage amplify with our ACT libs"
publish_to: none

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_flutter: ^2.6.4

  equatable: ^2.0.7

  # Contains the structure to create services and managers
  act_abstract_manager:
    path: ../act_abstract_manager

  act_config_manager:
    path: ../act_config_manager

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Contains the logger manager
  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
