# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_server_storage_ui
description: "Contains helpful widgets to work with act_server_storage_manager"
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Provide the configuration for the storage manager
  act_config_manager:
    path: ../act_config_manager

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

  # Storage manager
  act_server_storage_manager:
    path: ../act_server_storage_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
