# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_amplify_cognito
description: This is the package used to add cognito support to the mobile app
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # TODO(brolandeau): when updating the lib, verify if we still need to override `web`
  amplify_auth_cognito: ^2.6.1

  amplify_flutter: ^2.6.1

  aws_signature_v4: ^0.6.3

  equatable: ^2.0.5

  # The abstract manager
  act_abstract_manager:
    path: ../act_abstract_manager

  # This contains the amplify core library
  act_amplify_core:
    path: ../act_amplify_core

  # Extend Dart functionalities
  act_dart_utility:
    path: ../act_dart_utility

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # This is the logger manager
  act_logger_manager:
    path: ../act_logger_manager

  # Contains the shared authentication services, models, types, etc. to abstract authentication in
  # app
  act_shared_auth:
    path: ../act_shared_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  # For now, Amplify cognito depends on libs which depends of web: ^0.5.0 and firebase crashlytics
  # depends on web: ^1.0.0, we force the version of the web dependency
  web: ^1.0.0
