# SPDX-FileCopyrightText: 2024 Th√©o Magne <theo.magne@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_amplify_storage_s3
description: "This package is a wrapper around the Amplify Storage S3 plugin."
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_flutter: ^2.6.4

  amplify_storage_s3: ^2.6.4

  amplify_auth_cognito: ^2.6.4

  equatable: ^2.0.7

  flutter_cache_manager: ^3.4.1

  path_provider: ^2.1.5

  # Contains the structure to create services and managers
  act_abstract_manager:
    path: ../act_abstract_manager

  # This contains the amplify core library
  act_amplify_core:
    path: ../act_amplify_core

  act_config_manager:
    path: ../act_config_manager

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Contains the logger manager
  act_logger_manager:
    path: ../act_logger_manager

  # Storage manager with the AbstractStorageSergice that this package
  # will implement
  act_server_storage_manager:
    path: ../act_server_storage_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
