# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_http_core
description: This package contains the core HTTP functionalities
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  act_dart_utility:
    path: ../act_dart_utility

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
