# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_qr_code
description: This package contains a QR Code widget ready to use

publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_settings: ^6.1.1

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  flutter_bloc: ^9.1.1

  permission_handler: ^12.0.0+1

  qr_code_scanner: ^1.0.1

  act_dart_utility:
    path: ../act_dart_utility

  act_global_manager:
    path: ../act_global_manager

  act_music_player_manager:
    path: ../act_music_player_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^5.0.0
