# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_yaml_utility
description: This contains utility classes to manage YAML
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  yaml: ^3.1.3

  # Contains utilities for Dart
  act_dart_utility:
    path: ../act_dart_utility

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
